# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 the rules_hdl authors

package(
    default_applicable_licenses = ["//:package_license"],
    default_visibility = ["//visibility:private"],
)

licenses(["restricted"])
