# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: 100
  logStreamingOption: STREAM_ON
logsBucket: 'gs://bazel_rules_hdl'

steps:
# Access secrets from Secret Manager
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=buildbuddy-cert > /root/.ssh/buildbuddy-cert.pem
    gcloud secrets versions access latest --secret=buildbuddy-key > /root/.ssh/buildbuddy-key.pem
    gcloud secrets versions access latest --secret=github-app-key-cloud-build-status-reporter > /root/.ssh/github-app-key-cloud-build-status-reporter.pem
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Run the build
- name: marketplace.gcr.io/google/ubuntu2204 # Ubuntu 22.04
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y libtinfo5 clang libc6-dev curl git
    curl -fsSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.29.0/bazelisk-linux-amd64
    echo "5a408715e932c0250d28bd84555f12edbf70117de42f9181691c736eacc4a992  /usr/local/bin/bazel" | sha256sum -c -
    chmod +x /usr/local/bin/bazel
    export USE_BAZEL_VERSION=8.5.0
    BUILD_INVOCATION_ID=$(python3 tools/generate_uuid.py)
    TEST_INVOCATION_ID=$(python3 tools/generate_uuid.py)
    echo STATUS: Reporting logs with build invocation id $$BUILD_INVOCATION_ID and test invocation id $$TEST_INVOCATION_ID to GitHub.
    bazel run --config=ciremotebuild //tools:report_status_to_github -- \
        --head_sha=${COMMIT_SHA} \
        --build_invocation_id=$$BUILD_INVOCATION_ID \
        --test_invocation_id=$$TEST_INVOCATION_ID \
        --github_app_key_file=/root/.ssh/github-app-key-cloud-build-status-reporter.pem
    echo STATUS: Reported logs to GitHub.
    EXTRA_BAZEL_ARGS="--build_metadata=USER=${_USERNAME} \
        --config=ciremotebuild \
        --bes_results_url=https://app.buildbuddy.io/invocation/ \
        --noshow_progress" \
    EXTRA_BUILD_BAZEL_ARGS="--invocation_id=$$BUILD_INVOCATION_ID" \
    EXTRA_TEST_BAZEL_ARGS="--invocation_id=$$TEST_INVOCATION_ID \
                           --test_output=errors" \
        tools/test_everything.py
  timeout: 10800s
  volumes:
  - name: 'ssh'
    path: /root/.ssh

substitutions:
  _USERNAME: $(commit.author.login)
