timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
logsBucket: 'gs://bazel_rules_hdl'

steps:
# Access secrets from Secret Manager
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=buildbuddy-cert > /root/.ssh/buildbuddy-cert.pem
    gcloud secrets versions access latest --secret=buildbuddy-key > /root/.ssh/buildbuddy-key.pem
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Run the build
- name: l.gcr.io/google/bazel:3.5.0
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    bazel build --config=ciremotebuild //...
  timeout: 3600s
  volumes:
  - name: 'ssh'
    path: /root/.ssh
