"""Module extensions for rules_hdl."""

load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@rules_hdl//dependency_support/com_google_skywater_pdk:cell_libraries.bzl", "CELL_LIBRARIES")

def _build_file(library_name):
    return """
load("@rules_hdl//dependency_support/com_google_skywater_pdk:declare_cell_library.bzl", "declare_cell_library")
declare_cell_library("{}")
""".format(library_name)

def _pdks_extension_impl(ctx):
    # ASAP7 PDKs
    http_archive(
        name = "org_theopenroadproject_asap7_pdk_r1p7",
        urls = [
            "https://github.com/The-OpenROAD-Project/asap7_pdk_r1p7/archive/1ff7649bbf423207f6f70293dc1cf630cd477365.tar.gz",
        ],
        build_file = "@rules_hdl//dependency_support/org_theopenroadproject_asap7_pdk_r1p7:bundled.BUILD.bazel",
        type = "tar.gz",
        strip_prefix = "asap7_pdk_r1p7-1ff7649bbf423207f6f70293dc1cf630cd477365",
        sha256 = "b5847f93e55debb49d03ec581e22eb301109ff90c9ad19d35ae1223c70250391",
    )
    http_archive(
        name = "org_theopenroadproject_asap7sc6t_26",
        urls = [
            "https://github.com/The-OpenROAD-Project/asap7sc6t_26/archive/f572bf760c8bdc853cbafd0742790aba0780089c.tar.gz",
        ],
        build_file = "@rules_hdl//dependency_support/org_theopenroadproject_asap7sc6t_26:bundled.BUILD.bazel",
        type = "tar.gz",
        strip_prefix = "asap7sc6t_26-f572bf760c8bdc853cbafd0742790aba0780089c",
        sha256 = "4bfe15775eaab3a5cc443d444ef82bf7b9c818ba2ed948ce3d9cc6a4cfa1c36c",
    )
    http_archive(
        name = "org_theopenroadproject_asap7sc7p5t_27",
        urls = [
            "https://github.com/The-OpenROAD-Project/asap7sc7p5t_27/archive/900f55ed8bef025f39edcc8b8be5e04a2c55c15a.tar.gz",
        ],
        build_file = "@rules_hdl//dependency_support/org_theopenroadproject_asap7sc7p5t_27:bundled.BUILD.bazel",
        type = "tar.gz",
        strip_prefix = "asap7sc7p5t_27-900f55ed8bef025f39edcc8b8be5e04a2c55c15a",
        sha256 = "db5531736a34f34e919488468e8ee09ae87495ff8a6188fad375d68c19e10e20",
    )
    http_archive(
        name = "org_theopenroadproject_asap7sc7p5t_28",
        urls = [
            "https://github.com/The-OpenROAD-Project/asap7sc7p5t_28/archive/d88477438935a5a388bd6294f682dc405c93c5d2.tar.gz",
        ],
        build_file = "@rules_hdl//dependency_support/org_theopenroadproject_asap7sc7p5t_28:bundled.BUILD.bazel",
        type = "tar.gz",
        strip_prefix = "asap7sc7p5t_28-d88477438935a5a388bd6294f682dc405c93c5d2",
        sha256 = "7f028a41425b8d736958cae994b3c1722d4bef2c0d28f6bf507b9ac8138ecc41",
    )

    # Skywater PDK
    maybe(
        http_archive,
        name = "com_google_skywater_pdk",
        urls = [
            "https://github.com/google/skywater-pdk/archive/3d7617a1acb92ea883539bcf22a632d6361a5de4.tar.gz",  # 2020-12-04
        ],
        strip_prefix = "skywater-pdk-3d7617a1acb92ea883539bcf22a632d6361a5de4",
        sha256 = "49e5b03c26131a03eb038697d396a6ebf14058d78196f5d95c2bbdb0bdc8f32e",
        build_file = "@rules_hdl//dependency_support/com_google_skywater_pdk:bundled.BUILD.bazel",
        patches = [Label("//dependency_support/com_google_skywater_pdk:patches/fix-invalid-escape.patch")],
        patch_strip = 1,
    )

    for library_name in CELL_LIBRARIES:
        library = CELL_LIBRARIES[library_name]
        if library.get("library_type", None) == "ip_library":
            continue
        workspace_name = "com_google_skywater_pdk_" + library_name
        maybe(
            new_git_repository,
            name = workspace_name,
            commit = library["commit"],
            remote = "https://github.com/google/skywater-pdk-libs-%s.git" % library_name,
            shallow_since = library["shallow_since"],
            build_file_content = _build_file(library_name),
            patches = library.get("patches", []),
            # Strip one directory level. Useful for patches generated by git.
            patch_args = [
                "-p1",
            ],
        )

    return ctx.extension_metadata(
        root_module_direct_deps = [
            "org_theopenroadproject_asap7_pdk_r1p7",
            "org_theopenroadproject_asap7sc6t_26",
            "org_theopenroadproject_asap7sc7p5t_27",
            "org_theopenroadproject_asap7sc7p5t_28",
            "com_google_skywater_pdk",
        ] + ["com_google_skywater_pdk_" + lib for lib in CELL_LIBRARIES if CELL_LIBRARIES[lib].get("library_type", None) != "ip_library"],
        root_module_direct_dev_deps = [],
    )

pdks_extension = module_extension(
    implementation = _pdks_extension_impl,
    tag_classes = {
        "use_toolchain": tag_class(
            attrs = {
                "name": attr.string(mandatory = True),
            },
        ),
    },
)
