// Generated by CIRCT firtool-1.53.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module GenericSerializer_TestHarness_UNIQUIFIED(
  input         clock,
                reset,
                io_in_valid,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  input  [2:0]  io_in_bits_chanId,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
                io_in_bits_opcode,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
                io_in_bits_param,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  input  [7:0]  io_in_bits_size,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
                io_in_bits_source,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  input  [63:0] io_in_bits_address,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
                io_in_bits_data,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  input         io_in_bits_corrupt,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  input  [8:0]  io_in_bits_union,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  input         io_in_bits_last,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
                io_out_ready,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  output        io_in_ready,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
                io_out_valid,	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
  output [31:0] io_out_bits	// @[generators/testchipip/src/main/scala/Serdes.scala:166:14]
);

  reg  [163:0] data;	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17]
  reg          sending;	// @[generators/testchipip/src/main/scala/Serdes.scala:176:24]
  reg  [2:0]   sendCount;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  wire         wrap_wrap = sendCount == 3'h5;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :73:24]
  wire         _GEN = io_out_ready & sending;	// @[generators/testchipip/src/main/scala/Serdes.scala:176:24, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire         _GEN_0 = ~sending & io_in_valid;	// @[generators/testchipip/src/main/scala/Serdes.scala:176:24, :179:18, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  always @(posedge clock) begin
    if (_GEN)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      data <= {32'h0, data[163:32]};	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17, :189:37]
    else if (_GEN_0)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      data <= {io_in_bits_chanId, io_in_bits_opcode, io_in_bits_param, io_in_bits_size, io_in_bits_source, io_in_bits_address, io_in_bits_data, io_in_bits_corrupt, io_in_bits_union, io_in_bits_last};	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17, :185:24]
    if (reset) begin
      sending <= 1'h0;	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17, :176:24]
      sendCount <= 3'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    end
    else begin
      sending <= ~(_GEN & wrap_wrap) & (_GEN_0 | sending);	// @[186:13:176:24, generators/testchipip/src/main/scala/Serdes.scala:176:24, :184:21, :191:19, src/main/scala/chisel3/util/Counter.scala:73:24, src/main/scala/chisel3/util/Counter.scala 118:{16,23}:117:24, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      if (_GEN) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
        if (wrap_wrap)	// @[src/main/scala/chisel3/util/Counter.scala:73:24]
          sendCount <= 3'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
        else	// @[src/main/scala/chisel3/util/Counter.scala:73:24]
          sendCount <= sendCount + 3'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        data = {_RANDOM[3'h0], _RANDOM[3'h1], _RANDOM[3'h2], _RANDOM[3'h3], _RANDOM[3'h4], _RANDOM[3'h5][3:0]};	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17]
        sending = _RANDOM[3'h5][4];	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17, :176:24]
        sendCount = _RANDOM[3'h5][7:5];	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17, src/main/scala/chisel3/util/Counter.scala:61:40]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = ~sending;	// @[generators/testchipip/src/main/scala/Serdes.scala:176:24, :179:18]
  assign io_out_valid = sending;	// @[generators/testchipip/src/main/scala/Serdes.scala:176:24]
  assign io_out_bits = data[31:0];	// @[generators/testchipip/src/main/scala/Serdes.scala:174:17, :181:22]
endmodule

