// Generated by CIRCT firtool-1.53.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module TLMonitor_47(
  input       clock,
              reset,
              io_in_a_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
              io_in_a_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [2:0] io_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [8:0] io_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input       io_in_d_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
              io_in_d_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [2:0] io_in_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [1:0] io_in_d_bits_param,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
              io_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input       io_in_d_bits_source,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
              io_in_d_bits_sink,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
              io_in_d_bits_denied,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
              io_in_d_bits_corrupt	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
);

  wire [31:0] _plusarg_reader_1_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire [31:0] _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        _GEN = io_in_a_bits_opcode == 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:81:25]
  wire [4:0]  _GEN_0 = io_in_a_bits_address[6:2] ^ 5'h11;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:31]
  wire        _GEN_1 = io_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:104:25]
  wire        _GEN_2 = io_in_a_bits_address[8:6] == 3'h0 | {io_in_a_bits_address[8:7], _GEN_0[4:2], _GEN_0[0]} == 6'h0 | {io_in_a_bits_address[8:7], io_in_a_bits_address[6:3] ^ 4'hB} == 6'h0 | {io_in_a_bits_address[8:7], ~(io_in_a_bits_address[6:5])} == 4'h0 | {io_in_a_bits_address[8], ~(io_in_a_bits_address[7])} == 2'h0 | io_in_a_bits_address[8];	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:656:79, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:672:42, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire        _GEN_3 = io_in_a_bits_opcode == 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:130:25, :640:42]
  wire        _GEN_4 = io_in_a_bits_opcode == 3'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:138:25]
  wire        _GEN_5 = io_in_a_bits_opcode == 3'h5;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:146:25, :655:59]
  wire        _GEN_6 = io_in_d_bits_opcode != 3'h7;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:45:24, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:92:25]
  wire        d_release_ack = io_in_d_bits_opcode == 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:81:25, :310:25]
  wire        _GEN_7 = io_in_d_bits_param != 2'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26]
  wire        _GEN_8 = io_in_d_bits_param != 2'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:323:28]
  wire        _GEN_9 = ~io_in_d_bits_denied | io_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:315:15, :334:30]
  wire        a_first_done = io_in_a_ready & io_in_a_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg         a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  reg  [2:0]  opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
  reg  [2:0]  param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
  reg  [1:0]  size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
  reg         source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
  reg  [8:0]  address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
  wire        _GEN_10 = io_in_a_bits_opcode == opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22, :390:32]
  wire        _GEN_11 = size == 2'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22, :392:32]
  wire        _GEN_12 = io_in_a_bits_address == address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :394:32]
  reg         d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  reg  [2:0]  opcode_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:535:22]
  reg  [1:0]  param_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:536:22]
  reg  [1:0]  size_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
  reg         source_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
  reg         sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:539:22]
  reg         denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
  wire        _GEN_13 = io_in_d_bits_opcode == opcode_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:535:22, :542:29]
  wire        _GEN_14 = io_in_d_bits_param == param_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:536:22, :543:29]
  wire        _GEN_15 = io_in_d_bits_size == size_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :544:29]
  wire        _GEN_16 = io_in_d_bits_source == source_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22, :545:29]
  wire        _GEN_17 = io_in_d_bits_sink == sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:539:22, :546:29]
  wire        _GEN_18 = io_in_d_bits_denied == denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22, :547:29]
  reg         inflight;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27]
  reg  [3:0]  inflight_opcodes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35]
  reg  [3:0]  inflight_sizes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33]
  reg         a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  reg         d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire [3:0]  _GEN_19 = {1'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31, :634:69, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire [3:0]  _a_opcode_lookup_T_1 = inflight_opcodes >> _GEN_19;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :634:{44,69}, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire [3:0]  _a_size_lookup_T_1 = inflight_sizes >> _GEN_19;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33, :634:69, :638:40, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire        _GEN_20 = a_first_done & ~a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:652:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_21 = io_in_d_valid & ~d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:671:26]
  wire        _GEN_22 = _GEN_21 & ~d_release_ack;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:310:25, :671:{26,74}, :680:71]
  wire        same_cycle_resp = io_in_a_valid & ~a_first_counter_1 & ~io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:681:{88,113}]
  wire        _GEN_23 = inflight >> io_in_d_bits_source | same_cycle_resp;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :681:88, :682:{25,49}]
  wire        _GEN_24 = _GEN_1 | _GEN_4 | _GEN_3;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:104:25, :130:25, :138:25, :685:38]
  wire        _GEN_25 = io_in_d_bits_opcode == ((&io_in_a_bits_opcode) | _GEN ? 3'h4 : _GEN_5 ? 3'h2 : {2'h0, _GEN_24}) | io_in_d_bits_opcode == ((&io_in_a_bits_opcode) ? 3'h4 : _GEN ? 3'h5 : _GEN_5 ? 3'h2 : {2'h0, _GEN_24});	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:81:25, :92:25, :146:25, :640:42, :655:59, :685:{38,77}, :686:39]
  wire        _GEN_26 = io_in_d_bits_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:687:36]
  wire        _GEN_27 = _a_opcode_lookup_T_1[3:1] == 3'h4 | _a_opcode_lookup_T_1[3:1] == 3'h3 | _a_opcode_lookup_T_1[3:1] == 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:138:25, :634:{44,152}, :640:42, :689:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_28 = _a_opcode_lookup_T_1[3:1] == 3'h5;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:634:{44,152}, :655:59, :689:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_29 = _a_opcode_lookup_T_1[3:1] == 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:81:25, :634:{44,152}, :689:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_30 = io_in_d_bits_opcode == ((&(_a_opcode_lookup_T_1[3:1])) | _GEN_29 ? 3'h4 : _GEN_28 ? 3'h2 : {2'h0, _GEN_27}) | io_in_d_bits_opcode == ((&(_a_opcode_lookup_T_1[3:1])) ? 3'h4 : _GEN_29 ? 3'h5 : _GEN_28 ? 3'h2 : {2'h0, _GEN_27});	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:634:{44,152}, :640:42, :655:59, :689:{38,72}, :690:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire [3:0]  _GEN_31 = {2'h0, io_in_d_bits_size};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:691:36]
  wire        _GEN_32 = _GEN_31 == {1'h0, _a_size_lookup_T_1[3:1]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31, :638:{40,144}, :691:36, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala 636:33:638:19, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_33 = ~io_in_d_ready | io_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:695:{15,32}]
  reg  [31:0] watchdog;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
  wire        _GEN_34 = ~inflight | _plusarg_reader_out == 32'h0 | watchdog < _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:259:74, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :658:17, :706:27, :709:{39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  reg         inflight_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:723:35]
  reg  [3:0]  inflight_sizes_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:725:35]
  reg         d_first_counter_2;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire [3:0]  _c_size_lookup_T_1 = inflight_sizes_1 >> _GEN_19;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:634:69, :725:35, :747:42, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire        _GEN_35 = inflight_1 >> io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:723:35, :793:25]
  wire        _GEN_36 = _GEN_31 == {1'h0, _c_size_lookup_T_1[3:1]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31, :691:36, :747:{42,146}, :797:36, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala 745:35:747:21, src/main/scala/chisel3/util/OneHot.scala:65:12]
  reg  [31:0] watchdog_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:815:27]
  wire        _GEN_37 = ~inflight_1 | _plusarg_reader_1_out == 32'h0 | watchdog_1 < _plusarg_reader_1_out;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:259:74, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:723:35, :815:27, :818:{16,39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        _GEN_38 = io_in_a_valid & _GEN & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :81:25]
  wire        _GEN_39 = io_in_a_valid & (&io_in_a_bits_opcode) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :92:25]
  wire        _GEN_40 = io_in_a_valid & _GEN_1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :104:25]
  wire        _GEN_41 = io_in_a_valid & io_in_a_bits_opcode == 3'h0 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :114:25]
  wire        _GEN_42 = io_in_a_valid & io_in_a_bits_opcode == 3'h1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :122:25]
  wire        _GEN_43 = io_in_a_valid & _GEN_3 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :130:25]
  wire        _GEN_44 = io_in_a_valid & _GEN_4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :138:25]
  wire        _GEN_45 = io_in_a_valid & _GEN_5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :146:25]
  wire        _GEN_46 = io_in_d_valid & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
  wire        _GEN_47 = io_in_d_valid & d_release_ack & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :310:25]
  wire        _GEN_48 = io_in_d_valid & io_in_d_bits_opcode == 3'h4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :318:25]
  wire        _GEN_49 = io_in_d_valid & io_in_d_bits_opcode == 3'h5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :328:25, :655:59]
  wire        _GEN_50 = io_in_d_valid & io_in_d_bits_opcode == 3'h0 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :338:25]
  wire        _GEN_51 = io_in_d_valid & io_in_d_bits_opcode == 3'h1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :346:25]
  wire        _GEN_52 = io_in_d_valid & io_in_d_bits_opcode == 3'h2 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :354:25, :640:42]
  wire        _GEN_53 = io_in_a_valid & a_first_counter & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
  wire        _GEN_54 = io_in_d_valid & d_first_counter & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
  wire        _GEN_55 = _GEN_20 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :652:25]
  wire        _GEN_56 = _GEN_22 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :680:71]
  wire        _GEN_57 = _GEN_22 & same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :680:71, :681:88]
  wire        _GEN_58 = _GEN_22 & ~same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :680:71, :681:88]
  wire        _GEN_59 = _GEN_21 & ~a_first_counter_1 & io_in_a_valid & ~io_in_d_bits_source & ~d_release_ack & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :310:25, :671:{26,74}, :681:113]
  wire        _GEN_60 = io_in_d_valid & ~d_first_counter_2 & d_release_ack & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :310:25]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    wire _GEN_61 = (`PRINTF_COND_) & _GEN_39;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_38) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries AcquireBlock type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries AcquireBlock from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if ((`PRINTF_COND_) & _GEN_38 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel AcquireBlock address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if (_GEN_61) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries AcquirePerm type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries AcquirePerm from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      end
      if ((`PRINTF_COND_) & _GEN_39 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel AcquirePerm address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if (_GEN_61)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel AcquirePerm requests NtoB (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_40 & ~_GEN_2)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:672:42]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries Get type which slave claims it can't support (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_40 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel Get address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_41 & ~_GEN_2)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:672:42]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries PutFull type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_41 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel PutFull address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_42)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries PutPartial type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_42 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel PutPartial address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_43)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries Arithmetic type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_43 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel Arithmetic address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_44)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries Logical type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_44 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel Logical address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_45)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries Hint type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_45 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel Hint address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_46 & ~_GEN_6)	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:45:24, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel has invalid opcode (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_47 & io_in_d_bits_source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseAck carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_47 & ~(io_in_d_bits_size[1]))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :312:27]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseAck smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_47 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseeAck carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_47 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseAck is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_47 & io_in_d_bits_denied)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseAck is denied (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_48 & io_in_d_bits_source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_48)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant carries invalid sink ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_48 & ~(io_in_d_bits_size[1]))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :312:27]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_48 & ~_GEN_7)	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant carries invalid cap param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_48 & ~_GEN_8)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :323:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant carries toN param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_48 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_49 & io_in_d_bits_source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_49)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData carries invalid sink ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_49 & ~(io_in_d_bits_size[1]))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :312:27]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_49 & ~_GEN_7)	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData carries invalid cap param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_49 & ~_GEN_8)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :323:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData carries toN param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_49 & ~_GEN_9)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :334:30]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData is denied but not corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_50 & io_in_d_bits_source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAck carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_50 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAck carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_50 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAck is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_51 & io_in_d_bits_source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAckData carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_51 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAckData carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_51 & ~_GEN_9)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :334:30]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAckData is denied but not corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_52 & io_in_d_bits_source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel HintAck carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_52 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel HintAck carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_52 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel HintAck is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_53 & ~_GEN_10)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :390:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_53 & (|param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :385:22, :391:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel param changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_53 & ~_GEN_11)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :392:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_53 & source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :387:22]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_53 & ~_GEN_12)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :394:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel address changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_54 & ~_GEN_13)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :542:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_54 & ~_GEN_14)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :543:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel param changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_54 & ~_GEN_15)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :544:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_54 & ~_GEN_16)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :545:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_54 & ~_GEN_17)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :546:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel sink changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_54 & ~_GEN_18)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :547:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel denied changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_55 & inflight)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :611:27]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel re-used a source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_56 & ~_GEN_23)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :682:49]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_57 & ~_GEN_25)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :685:77]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_57 & ~_GEN_26)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :687:36]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_58 & ~_GEN_30)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :689:72]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_58 & ~_GEN_32)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :691:36]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_59 & ~_GEN_33)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :695:32]
        $fwrite(32'h80000002, "Assertion failed: ready check\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & ~reset & ~_GEN_34)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :709:47]
        $fwrite(32'h80000002, "Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_60 & ~_GEN_35)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :793:25]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_60 & ~_GEN_36)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :797:36]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & ~reset & ~_GEN_37)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :818:47]
        $fwrite(32'h80000002, "Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BusBypass.scala:32:12)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [30:0] _GEN_62 = {28'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:677:76]
  wire [30:0] _d_opcodes_clr_T_5 = 31'hF << _GEN_62;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:677:76]
  wire [30:0] _d_sizes_clr_T_5 = 31'hF << _GEN_62;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:677:76, :678:74]
  wire [30:0] _d_sizes_clr_T_11 = 31'hF << _GEN_62;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:677:76, :788:74]
  wire        _GEN_63 = a_first_done & ~a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:396:18, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        d_first_done = io_in_d_ready & io_in_d_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_64 = d_first_done & ~d_first_counter_1 & ~d_release_ack;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:310:25, :671:74, :675:70, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_65 = d_first_done & ~d_first_counter_2 & d_release_ack;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:310:25, :785:70, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  always @(posedge clock) begin
    if (_GEN_38) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_2: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_3: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_6: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end
    if (_GEN_39) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_10: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_11: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_14: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_16: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
    end
    if (_GEN_40) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_20: assert(_GEN_2);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:672:42]
      assert__assert_22: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end
    if (_GEN_41) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_26: assert(_GEN_2);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:672:42]
      assert__assert_28: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end
    if (_GEN_42) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_31: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_33: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end
    if (_GEN_43) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_36: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_38: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end
    if (_GEN_44) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_41: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_43: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end
    if (_GEN_45) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_46: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      assert__assert_48: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end
    if (_GEN_46)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_52: assert(_GEN_6);	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:45:24, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
    if (_GEN_47) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_53: assert(~io_in_d_bits_source);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_54: assert(io_in_d_bits_size[1]);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :312:27]
      assert__assert_55: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_56: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
      assert__assert_57: assert(~io_in_d_bits_denied);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :315:15]
    end
    if (_GEN_48) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_58: assert(~io_in_d_bits_source);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_59: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :99:31]
      assert__assert_60: assert(io_in_d_bits_size[1]);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :312:27]
      assert__assert_61: assert(_GEN_7);	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_62: assert(_GEN_8);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :323:28]
      assert__assert_63: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
    end
    if (_GEN_49) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_65: assert(~io_in_d_bits_source);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_66: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :99:31]
      assert__assert_67: assert(io_in_d_bits_size[1]);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :312:27]
      assert__assert_68: assert(_GEN_7);	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_69: assert(_GEN_8);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :323:28]
      assert__assert_70: assert(_GEN_9);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :334:30]
    end
    if (_GEN_50) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_72: assert(~io_in_d_bits_source);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_73: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_74: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
    end
    if (_GEN_51) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_76: assert(~io_in_d_bits_source);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_77: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_78: assert(_GEN_9);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :334:30]
    end
    if (_GEN_52) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_80: assert(~io_in_d_bits_source);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_81: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_82: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
    end
    if (_GEN_53) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_87: assert(_GEN_10);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :390:32]
      assert__assert_88: assert(~(|param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :385:22, :391:32]
      assert__assert_89: assert(_GEN_11);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :392:32]
      assert__assert_90: assert(~source);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :387:22, :393:32]
      assert__assert_91: assert(_GEN_12);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :394:32]
    end
    if (_GEN_54) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_92: assert(_GEN_13);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :542:29]
      assert__assert_93: assert(_GEN_14);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :543:29]
      assert__assert_94: assert(_GEN_15);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :544:29]
      assert__assert_95: assert(_GEN_16);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :545:29]
      assert__assert_96: assert(_GEN_17);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :546:29]
      assert__assert_97: assert(_GEN_18);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :547:29]
    end
    if (_GEN_55)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_98: assert(~inflight);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :611:27, :658:17]
    if (_GEN_56)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_99: assert(_GEN_23);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :682:49]
    if (_GEN_57) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_100: assert(_GEN_25);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :685:77]
      assert__assert_101: assert(_GEN_26);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :687:36]
    end
    if (_GEN_58) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_102: assert(_GEN_30);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :689:72]
      assert__assert_103: assert(_GEN_32);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :691:36]
    end
    if (_GEN_59)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_104: assert(_GEN_33);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :695:32]
    if (~reset)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_105: assert(_GEN_34);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :709:47]
    if (_GEN_60) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_107: assert(_GEN_35);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :793:25]
      assert__assert_109: assert(_GEN_36);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :797:36]
    end
    if (~reset)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_111: assert(_GEN_37);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :818:47]
    if (reset) begin
      a_first_counter <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      d_first_counter <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      inflight <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31, :611:27]
      inflight_opcodes <= 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :656:79, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      inflight_sizes <= 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33, :656:79, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      a_first_counter_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      d_first_counter_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:259:74, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
      inflight_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31, :723:35]
      inflight_sizes_1 <= 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:656:79, :725:35, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      d_first_counter_2 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31]
      watchdog_1 <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:259:74, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:815:27]
    end
    else begin
      a_first_counter <= (~a_first_done | a_first_counter - 1'h1) & a_first_counter;	// @[237:15:230:27, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28, :236:17, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      d_first_counter <= (~d_first_done | d_first_counter - 1'h1) & d_first_counter;	// @[237:15:230:27, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28, :236:17, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      inflight <= (inflight | _GEN_20) & ~(_GEN_64 & ~io_in_d_bits_source);	// @[676:21:661:34, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :652:25, :675:{70,89}, :702:{27,36,38}, src/main/scala/chisel3/util/OneHot.scala:58:35]
      inflight_opcodes <= (inflight_opcodes | (_GEN_20 ? {io_in_a_bits_opcode, 1'h1} : 4'h0)) & ~(_GEN_64 ? _d_opcodes_clr_T_5[3:0] : 4'h0);	// @[656:28:627:33, 677:21:665:33, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :92:38, generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, :141:33, :148:30, :161:28, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :88:31, :89:18, :100:31, :109:31, :110:30, :127:40, :613:35, :652:{25,70}, :654:61, :656:79, :675:{70,89}, :677:76, :703:{43,60,62}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1161:30, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      inflight_sizes <= (inflight_sizes | (_GEN_20 ? {1'h0, _GEN_20 ? 3'h5 : 3'h0} : 4'h0)) & ~(_GEN_64 ? _d_sizes_clr_T_5[3:0] : 4'h0);	// @[655:28:645:38, 657:28:629:31, 678:21:667:31, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :99:31, :615:33, :652:{25,70}, :655:59, :656:79, :657:52, :675:{70,89}, :678:74, :704:{39,54,56}, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      a_first_counter_1 <= (~a_first_done | a_first_counter_1 - 1'h1) & a_first_counter_1;	// @[237:15:230:27, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28, :236:17, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      d_first_counter_1 <= (~d_first_done | d_first_counter_1 - 1'h1) & d_first_counter_1;	// @[237:15:230:27, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28, :236:17, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      if (a_first_done | d_first_done)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:712:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:259:74, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
      else	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:712:25]
        watchdog <= watchdog + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :711:26]
      inflight_1 <= inflight_1 & ~(_GEN_65 & ~io_in_d_bits_source);	// @[786:21:771:34, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:723:35, :785:{70,88}, :811:{44,46}, src/main/scala/chisel3/util/OneHot.scala:58:35]
      inflight_sizes_1 <= inflight_sizes_1 & ~(_GEN_65 ? _d_sizes_clr_T_11[3:0] : 4'h0);	// @[788:21:774:34, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:656:79, :725:35, :785:{70,88}, :788:74, :813:{56,58}, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      d_first_counter_2 <= (~d_first_done | d_first_counter_2 - 1'h1) & d_first_counter_2;	// @[237:15:230:27, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28, :236:17, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      if (d_first_done)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
        watchdog_1 <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:259:74, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:815:27]
      else	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
        watchdog_1 <= watchdog_1 + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:711:26, :815:27, :820:26]
    end
    if (_GEN_63) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:396:18]
      opcode <= io_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
      param <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
      size <= 2'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
      address <= io_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
    end
    source <= ~_GEN_63 & source;	// @[400:15:387:22, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22, :396:{18,30}]
    if (d_first_done & ~d_first_counter) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:549:18, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      opcode_1 <= io_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:535:22]
      param_1 <= io_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:536:22]
      size_1 <= io_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
      source_1 <= io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
      sink <= io_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:539:22]
      denied <= io_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        a_first_counter = _RANDOM[2'h0][0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
        opcode = _RANDOM[2'h0][3:1];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
        param = _RANDOM[2'h0][6:4];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
        size = _RANDOM[2'h0][8:7];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
        source = _RANDOM[2'h0][9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
        address = _RANDOM[2'h0][18:10];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
        d_first_counter = _RANDOM[2'h0][19];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
        opcode_1 = _RANDOM[2'h0][22:20];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:535:22]
        param_1 = _RANDOM[2'h0][24:23];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:536:22]
        size_1 = _RANDOM[2'h0][26:25];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
        source_1 = _RANDOM[2'h0][27];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
        sink = _RANDOM[2'h0][28];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:539:22]
        denied = _RANDOM[2'h0][29];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
        inflight = _RANDOM[2'h0][30];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27]
        inflight_opcodes = {_RANDOM[2'h0][31], _RANDOM[2'h1][2:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35]
        inflight_sizes = _RANDOM[2'h1][6:3];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :615:33]
        a_first_counter_1 = _RANDOM[2'h1][7];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35]
        d_first_counter_1 = _RANDOM[2'h1][8];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35]
        watchdog = {_RANDOM[2'h1][31:9], _RANDOM[2'h2][8:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :706:27]
        inflight_1 = _RANDOM[2'h2][9];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :723:35]
        inflight_sizes_1 = _RANDOM[2'h2][17:14];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :725:35]
        d_first_counter_2 = _RANDOM[2'h2][19];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
        watchdog_1 = {_RANDOM[2'h2][31:20], _RANDOM[2'h3][19:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :815:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader_1 (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_1_out)
  );
endmodule

