// Generated by CIRCT firtool-1.53.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module TLMonitor_18(
  input        clock,
               reset,
               io_in_a_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_a_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [28:0] io_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input        io_in_d_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [2:0]  io_in_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [1:0]  io_in_d_bits_param,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input [3:0]  io_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
  input        io_in_d_bits_sink,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_d_bits_denied,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
               io_in_d_bits_corrupt	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
);

  wire [31:0] _plusarg_reader_1_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire [31:0] _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        mask_eq_2 = ~(io_in_a_bits_address[2]) & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        mask_eq_3 = ~(io_in_a_bits_address[2]) & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        mask_eq_4 = io_in_a_bits_address[2] & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        mask_eq_5 = io_in_a_bits_address[2] & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        _GEN = {io_in_a_bits_address[2] | mask_eq_5 & io_in_a_bits_address[0], io_in_a_bits_address[2] | mask_eq_5 & ~(io_in_a_bits_address[0]), io_in_a_bits_address[2] | mask_eq_4 & io_in_a_bits_address[0], io_in_a_bits_address[2] | mask_eq_4 & ~(io_in_a_bits_address[0]), ~(io_in_a_bits_address[2]) | mask_eq_3 & io_in_a_bits_address[0], ~(io_in_a_bits_address[2]) | mask_eq_3 & ~(io_in_a_bits_address[0]), ~(io_in_a_bits_address[2]) | mask_eq_2 & io_in_a_bits_address[0], ~(io_in_a_bits_address[2]) | mask_eq_2 & ~(io_in_a_bits_address[0])} == 8'hF;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :110:30, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10]
  wire        _GEN_0 = {io_in_a_bits_address[28:14], ~(io_in_a_bits_address[13:12])} == 17'h0 | {io_in_a_bits_address[28:15], io_in_a_bits_address[13:12]} == 16'h0 | {io_in_a_bits_address[28:21], io_in_a_bits_address[20:17] ^ 4'h8, io_in_a_bits_address[15:12]} == 16'h0 | {io_in_a_bits_address[28:26], io_in_a_bits_address[25:16] ^ 10'h200} == 13'h0 | {io_in_a_bits_address[28:26], io_in_a_bits_address[25:12] ^ 14'h2010} == 17'h0 | {io_in_a_bits_address[28], ~(io_in_a_bits_address[27:26])} == 3'h0 | io_in_a_bits_address[28:12] == 17'h10020;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:673:26]
  wire        _GEN_1 = io_in_d_bits_opcode != 3'h7;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:45:24]
  wire        d_release_ack = io_in_d_bits_opcode == 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:310:25]
  wire        _GEN_2 = io_in_d_bits_size > 4'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :312:27]
  wire        _GEN_3 = io_in_d_bits_param != 2'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26]
  wire        _GEN_4 = io_in_d_bits_param != 2'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:323:28]
  wire        _GEN_5 = ~io_in_d_bits_denied | io_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:315:15, :334:30]
  wire        _GEN_6 = io_in_d_bits_opcode == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:338:25]
  wire        _a_first_T_1 = io_in_a_ready & io_in_a_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [8:0]  a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  reg  [2:0]  opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
  reg  [2:0]  param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
  reg  [3:0]  size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
  reg         source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
  reg  [28:0] address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
  wire        _GEN_7 = size == 4'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :386:22, :392:32]
  wire        _GEN_8 = io_in_a_bits_address == address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :394:32]
  reg  [8:0]  d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  reg  [2:0]  opcode_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:535:22]
  reg  [1:0]  param_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:536:22]
  reg  [3:0]  size_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
  reg         source_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22]
  reg         sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:539:22]
  reg         denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
  wire        _GEN_9 = io_in_d_bits_opcode == opcode_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:535:22, :542:29]
  wire        _GEN_10 = io_in_d_bits_param == param_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:536:22, :543:29]
  wire        _GEN_11 = io_in_d_bits_size == size_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :544:29]
  wire        _GEN_12 = io_in_d_bits_sink == sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:539:22, :546:29]
  wire        _GEN_13 = io_in_d_bits_denied == denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22, :547:29]
  reg         inflight;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27]
  reg  [3:0]  inflight_opcodes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35]
  reg  [7:0]  inflight_sizes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33]
  reg  [8:0]  a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire        a_first_1 = a_first_counter_1 == 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27, :232:25]
  reg  [8:0]  d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire        d_first_1 = d_first_counter_1 == 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27, :232:25]
  wire        _same_cycle_resp_T_1 = io_in_a_valid & a_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:648:26]
  wire        _GEN_14 = _a_first_T_1 & a_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:652:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_15 = io_in_d_valid & d_first_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:671:26]
  wire        _GEN_16 = _GEN_15 & ~d_release_ack;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:310:25, :671:{26,71,74}]
  wire        _GEN_17 = inflight | _same_cycle_resp_T_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :648:26, :682:49]
  wire        _GEN_18 = io_in_d_bits_size == 4'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :687:36]
  wire        _GEN_19 = inflight_opcodes[3:1] == 3'h4 | inflight_opcodes[3:1] == 3'h3 | inflight_opcodes[3:1] == 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :634:152, :689:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_20 = inflight_opcodes[3:1] == 3'h5;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :634:152, :689:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_21 = inflight_opcodes[3:1] == 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :634:152, :689:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_22 = io_in_d_bits_opcode == ((&(inflight_opcodes[3:1])) | _GEN_21 ? 3'h4 : _GEN_20 ? 3'h2 : {2'h0, _GEN_19}) | io_in_d_bits_opcode == ((&(inflight_opcodes[3:1])) ? 3'h4 : _GEN_21 ? 3'h5 : _GEN_20 ? 3'h2 : {2'h0, _GEN_19});	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:312:27, :613:35, :634:152, :689:{38,72}, :690:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire [7:0]  _GEN_23 = {4'h0, io_in_d_bits_size};	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:634:69, :638:65, :656:79, :657:77, :691:36, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire        _GEN_24 = _GEN_23 == {1'h0, inflight_sizes[7:1]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :88:31, :99:31, :100:31, :615:33, :638:144, :691:36, :695:15, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala 636:33:638:19, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :215:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _GEN_25 = _same_cycle_resp_T_1 != _GEN_16 | ~_same_cycle_resp_T_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:648:26, :671:71, :699:{29,48,51}]
  reg  [31:0] watchdog;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
  wire        _GEN_26 = ~inflight | _plusarg_reader_out == 32'h0 | watchdog < _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :658:17, :706:27, :709:{39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  reg         inflight_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:723:35]
  reg  [7:0]  inflight_sizes_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:725:35]
  reg  [8:0]  d_first_counter_2;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire        d_first_2 = d_first_counter_2 == 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27, :232:25]
  wire        _GEN_27 = io_in_d_valid & d_first_2 & d_release_ack;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:310:25, :785:70]
  wire        _GEN_28 = _GEN_23 == {1'h0, inflight_sizes_1[7:1]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :88:31, :99:31, :100:31, :691:36, :695:15, :725:35, :747:146, :797:36, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala 745:35:747:21, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :215:38, src/main/scala/chisel3/util/OneHot.scala:65:12]
  reg  [31:0] watchdog_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:815:27]
  wire        _GEN_29 = ~inflight_1 | _plusarg_reader_1_out == 32'h0 | watchdog_1 < _plusarg_reader_1_out;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :706:27, :723:35, :815:27, :818:{39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        _GEN_30 = io_in_a_valid & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
  wire        _GEN_31 = io_in_d_valid & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
  wire        _GEN_32 = io_in_d_valid & d_release_ack & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :310:25]
  wire        _GEN_33 = io_in_d_valid & io_in_d_bits_opcode == 3'h4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :318:25]
  wire        _GEN_34 = io_in_d_valid & io_in_d_bits_opcode == 3'h5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :328:25]
  wire        _GEN_35 = io_in_d_valid & _GEN_6 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :338:25]
  wire        _GEN_36 = io_in_d_valid & io_in_d_bits_opcode == 3'h1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :346:25]
  wire        _GEN_37 = io_in_d_valid & io_in_d_bits_opcode == 3'h2 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :354:25]
  wire        _GEN_38 = io_in_a_valid & (|a_first_counter) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
  wire        _GEN_39 = io_in_d_valid & (|d_first_counter) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
  wire        _GEN_40 = _GEN_14 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :652:25]
  wire        _GEN_41 = _GEN_16 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :671:71]
  wire        _GEN_42 = _GEN_16 & _same_cycle_resp_T_1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :648:26, :671:71]
  wire        _GEN_43 = _GEN_16 & ~_same_cycle_resp_T_1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :648:26, :671:71, :699:51]
  wire        _GEN_44 = _GEN_15 & a_first_1 & io_in_a_valid & ~d_release_ack & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :310:25, :671:{26,74}]
  wire        _GEN_45 = _GEN_27 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :785:70]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_30 & ~_GEN_0)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:673:26]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel carries PutFull type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_30 & (|(io_in_a_bits_address[1:0])))	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel PutFull address not aligned to size (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_30 & ~_GEN)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :110:30]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel PutFull contains invalid mask (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_31 & ~_GEN_1)	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:45:24, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel has invalid opcode (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_32 & ~_GEN_2)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :312:27]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseAck smaller than a beat (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_32 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseeAck carries invalid param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_32 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseAck is corrupt (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_32 & io_in_d_bits_denied)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel ReleaseAck is denied (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_33)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant carries invalid sink ID (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_33 & ~_GEN_2)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :312:27]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant smaller than a beat (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_33 & ~_GEN_3)	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant carries invalid cap param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_33 & ~_GEN_4)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :323:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant carries toN param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_33 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel Grant is corrupt (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_34)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData carries invalid sink ID (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_34 & ~_GEN_2)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :312:27]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData smaller than a beat (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_34 & ~_GEN_3)	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData carries invalid cap param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_34 & ~_GEN_4)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :323:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData carries toN param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_34 & ~_GEN_5)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :334:30]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel GrantData is denied but not corrupt (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_35 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAck carries invalid param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_35 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAck is corrupt (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_36 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAckData carries invalid param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_36 & ~_GEN_5)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :334:30]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel AccessAckData is denied but not corrupt (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_37 & (|io_in_d_bits_param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :313:28]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel HintAck carries invalid param (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_37 & io_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel HintAck is corrupt (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_38 & (|opcode))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :384:22, :390:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_38 & (|param))	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :385:22, :391:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel param changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_38 & ~_GEN_7)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :392:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_38 & source)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :387:22]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_38 & ~_GEN_8)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :394:32]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel address changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_39 & ~_GEN_9)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :542:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_39 & ~_GEN_10)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :543:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel param changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_39 & ~_GEN_11)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :544:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_39 & source_1)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :538:22]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_39 & ~_GEN_12)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :546:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel sink changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_39 & ~_GEN_13)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :547:29]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel denied changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_40 & inflight)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :611:27]
        $fwrite(32'h80000002, "Assertion failed: 'A' channel re-used a source ID (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_41 & ~_GEN_17)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :682:49]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_42 & ~_GEN_6)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :338:25]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_42 & ~_GEN_18)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :687:36]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_43 & ~_GEN_22)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :689:72]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_43 & ~_GEN_24)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :691:36]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_44 & ~io_in_a_ready)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
        $fwrite(32'h80000002, "Assertion failed: ready check\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & ~reset & ~_GEN_25)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :699:48]
        $fwrite(32'h80000002, "Assertion failed: 'A' and 'D' concurrent, despite minlatency 2 (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & ~reset & ~_GEN_26)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :709:47]
        $fwrite(32'h80000002, "Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      if ((`PRINTF_COND_) & _GEN_45 & ~inflight_1)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :723:35]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & _GEN_45 & ~_GEN_28)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11, :797:36]
        $fwrite(32'h80000002, "Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :49:11]
      if ((`PRINTF_COND_) & ~reset & ~_GEN_29)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :818:47]
        $fwrite(32'h80000002, "Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:90:33)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [26:0] _GEN_46 = {23'h0, io_in_d_bits_size};	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [26:0] _d_first_beats1_decode_T_1 = 27'hFFF << _GEN_46;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [26:0] _d_first_beats1_decode_T_5 = 27'hFFF << _GEN_46;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [26:0] _d_first_beats1_decode_T_9 = 27'hFFF << _GEN_46;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire        _GEN_47 = _a_first_T_1 & ~(|a_first_counter);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:396:18, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_48 = io_in_d_valid & ~(|d_first_counter);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:549:18]
  always @(posedge clock) begin
    if (_GEN_30) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_26: assert(_GEN_0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:673:26]
      assert__assert_28: assert(~(|(io_in_a_bits_address[1:0])));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:22:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_30: assert(_GEN);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :110:30]
    end
    if (_GEN_31)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_52: assert(_GEN_1);	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:45:24, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
    if (_GEN_32) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_54: assert(_GEN_2);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :312:27]
      assert__assert_55: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_56: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
      assert__assert_57: assert(~io_in_d_bits_denied);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :315:15]
    end
    if (_GEN_33) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_59: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :88:31, :99:31, :100:31, :695:15, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :215:38]
      assert__assert_60: assert(_GEN_2);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :312:27]
      assert__assert_61: assert(_GEN_3);	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_62: assert(_GEN_4);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :323:28]
      assert__assert_63: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
    end
    if (_GEN_34) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_66: assert(1'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :88:31, :99:31, :100:31, :695:15, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :215:38]
      assert__assert_67: assert(_GEN_2);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :312:27]
      assert__assert_68: assert(_GEN_3);	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:105:26, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_69: assert(_GEN_4);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :323:28]
      assert__assert_70: assert(_GEN_5);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :334:30]
    end
    if (_GEN_35) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_73: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_74: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
    end
    if (_GEN_36) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_77: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_78: assert(_GEN_5);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :334:30]
    end
    if (_GEN_37) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_81: assert(~(|io_in_d_bits_param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :313:28]
      assert__assert_82: assert(~io_in_d_bits_corrupt);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :314:15]
    end
    if (_GEN_38) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_87: assert(~(|opcode));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :384:22, :390:32]
      assert__assert_88: assert(~(|param));	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :385:22, :391:32]
      assert__assert_89: assert(_GEN_7);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :392:32]
      assert__assert_90: assert(~source);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :387:22, :393:32]
      assert__assert_91: assert(_GEN_8);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :394:32]
    end
    if (_GEN_39) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_92: assert(_GEN_9);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :542:29]
      assert__assert_93: assert(_GEN_10);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :543:29]
      assert__assert_94: assert(_GEN_11);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :544:29]
      assert__assert_95: assert(~source_1);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :538:22, :545:29]
      assert__assert_96: assert(_GEN_12);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :546:29]
      assert__assert_97: assert(_GEN_13);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :547:29]
    end
    if (_GEN_40)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_98: assert(~inflight);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :611:27, :658:17]
    if (_GEN_41)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_99: assert(_GEN_17);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :682:49]
    if (_GEN_42) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_100: assert(_GEN_6);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :338:25]
      assert__assert_101: assert(_GEN_18);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :687:36]
    end
    if (_GEN_43) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_102: assert(_GEN_22);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :689:72]
      assert__assert_103: assert(_GEN_24);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :691:36]
    end
    if (_GEN_44)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_104: assert(io_in_a_ready);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
    if (~reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_105: assert(_GEN_25);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :699:48]
      assert__assert_106: assert(_GEN_26);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :709:47]
    end
    if (_GEN_45) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11]
      assert__assert_108: assert(inflight_1);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :723:35]
      assert__assert_110: assert(_GEN_28);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:49:11, :797:36]
    end
    if (~reset)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11]
      assert__assert_113: assert(_GEN_29);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:42:11, :818:47]
    if (reset) begin
      a_first_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
      d_first_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
      inflight <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :88:31, :99:31, :100:31, :611:27, :695:15, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :215:38]
      inflight_opcodes <= 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :634:69, :638:65, :656:79, :657:77, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      inflight_sizes <= 8'h0;	// @[657:28:629:31, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33, :652:70]
      a_first_counter_1 <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
      d_first_counter_1 <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
      watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
      inflight_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :42:11, :49:11, :88:31, :99:31, :100:31, :695:15, :723:35, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :215:38]
      inflight_sizes_1 <= 8'h0;	// @[657:28:629:31, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:652:70, :725:35]
      d_first_counter_2 <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
      watchdog_1 <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :815:27]
    end
    else begin
      if (_a_first_T_1) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
        if (|a_first_counter)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25]
          a_first_counter <= a_first_counter - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          a_first_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
        if (a_first_1)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          a_first_counter_1 <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          a_first_counter_1 <= a_first_counter_1 - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
      end
      if (io_in_d_valid) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
        if (|d_first_counter)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25]
          d_first_counter <= d_first_counter - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
        else if (io_in_d_bits_opcode[0])	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36]
          d_first_counter <= ~(_d_first_beats1_decode_T_1[11:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36]
          d_first_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
        if (d_first_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          if (io_in_d_bits_opcode[0])	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36]
            d_first_counter_1 <= ~(_d_first_beats1_decode_T_5[11:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
          else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36]
            d_first_counter_1 <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
        end
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          d_first_counter_1 <= d_first_counter_1 - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
        if (d_first_2) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          if (io_in_d_bits_opcode[0])	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36]
            d_first_counter_2 <= ~(_d_first_beats1_decode_T_9[11:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
          else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36]
            d_first_counter_2 <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
        end
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          d_first_counter_2 <= d_first_counter_2 - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
        watchdog_1 <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :815:27]
      end
      else	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14]
        watchdog_1 <= watchdog_1 + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:711:26, :815:27, :820:26]
      inflight <= (inflight | _GEN_14) & ~_GEN_16;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:611:27, :652:25, :671:71, :702:{27,36,38}]
      inflight_opcodes <= (inflight_opcodes | (_GEN_14 ? {3'h0, _GEN_14} : 4'h0)) & ~{4{_GEN_16}};	// @[656:28:627:33, 677:21:665:33, generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:613:35, :634:69, :638:65, :652:{25,70}, :656:{54,79}, :657:77, :665:33, :671:71, :675:89, :703:{43,60,62}, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      inflight_sizes <= (inflight_sizes | (_GEN_14 ? {3'h0, _GEN_14 ? 5'h5 : 5'h0} : 8'h0)) & ~{8{_GEN_16}};	// @[655:28:645:38, 657:28:629:31, 678:21:667:31, generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:615:33, :634:69, :638:65, :652:{25,70}, :655:59, :656:79, :657:{52,77}, :667:31, :671:71, :675:89, :704:{39,54,56}, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      if (_a_first_T_1 | io_in_d_valid)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:712:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
      else	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:712:25]
        watchdog <= watchdog + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :711:26]
      inflight_1 <= inflight_1 & ~_GEN_27;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:723:35, :785:70, :811:{44,46}]
      inflight_sizes_1 <= inflight_sizes_1 & ~{8{_GEN_27}};	// @[788:21:774:34, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:725:35, :774:34, :785:{70,88}, :813:{56,58}]
    end
    if (_GEN_47) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:396:18]
      opcode <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
      param <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
      size <= 4'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:17:14, :386:22]
      address <= io_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
    end
    source <= ~_GEN_47 & source;	// @[400:15:387:22, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22, :396:{18,30}]
    if (_GEN_48) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:549:18]
      opcode_1 <= io_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:535:22]
      param_1 <= io_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:536:22]
      size_1 <= io_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
      sink <= io_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:539:22]
      denied <= io_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
    end
    source_1 <= ~_GEN_48 & source_1;	// @[553:15:538:22, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:538:22, :549:{18,30}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        a_first_counter = _RANDOM[3'h0][8:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
        opcode = _RANDOM[3'h0][11:9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:384:22]
        param = _RANDOM[3'h0][14:12];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:385:22]
        size = _RANDOM[3'h0][18:15];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:386:22]
        source = _RANDOM[3'h0][19];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
        address = {_RANDOM[3'h0][31:20], _RANDOM[3'h1][16:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
        d_first_counter = _RANDOM[3'h1][25:17];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
        opcode_1 = _RANDOM[3'h1][28:26];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :535:22]
        param_1 = _RANDOM[3'h1][30:29];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :536:22]
        size_1 = {_RANDOM[3'h1][31], _RANDOM[3'h2][2:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22, :537:22]
        source_1 = _RANDOM[3'h2][3];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :538:22]
        sink = _RANDOM[3'h2][4];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :539:22]
        denied = _RANDOM[3'h2][5];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :540:22]
        inflight = _RANDOM[3'h2][6];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :611:27]
        inflight_opcodes = _RANDOM[3'h2][10:7];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :613:35]
        inflight_sizes = _RANDOM[3'h2][18:11];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22, :615:33]
        a_first_counter_1 = _RANDOM[3'h2][27:19];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
        d_first_counter_1 = {_RANDOM[3'h2][31:28], _RANDOM[3'h3][4:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:537:22]
        watchdog = {_RANDOM[3'h3][31:5], _RANDOM[3'h4][4:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
        inflight_1 = _RANDOM[3'h4][5];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :723:35]
        inflight_sizes_1 = _RANDOM[3'h4][17:10];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27, :725:35]
        d_first_counter_2 = {_RANDOM[3'h4][31:27], _RANDOM[3'h5][3:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:706:27]
        watchdog_1 = {_RANDOM[3'h5][31:4], _RANDOM[3'h6][3:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:815:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader_1 (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_1_out)
  );
endmodule

