load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_python//python:defs.bzl", "py_binary")

cc_binary(
    name = "verilator_process_wrapper",
    srcs = ["verilator_process_wrapper.cc"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "verilator_run_wrapper",
    srcs = ["verilator_run_wrapper.py"],
    visibility = ["//visibility:public"],
)
