# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_hdl//pdk/proto:build_defs.bzl", "extract_lef_and_liberty")

package(
    default_applicable_licenses = ["//:package_license"],
    default_visibility = ["//visibility:private"],
)

extract_lef_and_liberty(
    name = "asap7-sc7p5t_rev27_lvt_data",
    standard_cell = "@org_theopenroadproject_asap7sc6t_26//:asap7-sc7p5t_rev27_lvt",
)

extract_lef_and_liberty(
    name = "asap7-sc7p5t_rev27_rvt_data",
    standard_cell = "@org_theopenroadproject_asap7sc6t_26//:asap7-sc7p5t_rev27_rvt",
)

extract_lef_and_liberty(
    name = "asap7-sc7p5t_rev27_slvt_data",
    standard_cell = "@org_theopenroadproject_asap7sc6t_26//:asap7-sc7p5t_rev27_slvt",
)

extract_lef_and_liberty(
    name = "asap7-sc7p5t_rev27_rvt_4x_data",
    standard_cell = "@org_theopenroadproject_asap7sc6t_26//:asap7-sc7p5t_rev27_rvt_4x",
)